version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: library_postgres
    environment:
      POSTGRES_DB: library_db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - library_network

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: library_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@library.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - library_network

volumes:
  postgres_data:

networks:
  library_network:
    driver: bridge 